application: namolokamaoc1
version: 1
runtime: python
api_version: 1


handlers:
  - url: /image
    static_dir: image

  - url: /style
    static_dir: style

  - url: /scripts
    static_dir: scripts

  - url: /favicon\.ico
    static_files: favicon.ico
    upload: favicon\.ico

  - url: /report/.*
    script: main.py
    login: admin

  - url: .*
    script: main.py
